### ISSUE TITLE
Mapping of Mitigations with other controls (E.g. ISO 27001)

### ISSUE THREAD

**Issue by mariomjg99** [usnistgov/mobile-threat-catalogue#275] opened 2019-07-29 13:03 UTC
General Comment

**Proposed Change**:
Next to each mitigation in each mobile threat I would implement controls such as ISO 27001, ... 
I think this would be very helpful in many occasions.

**Comment by jajmo** [comment] 2019-07-30 15:36
Thank you for your feedback. However, this appears to be a duplicate of #14. By integrating the Cybersecurity Framework, we will inherently map to other standards, such as ISO and COBOL.

If you feel like this should be a separate issue, feel free to re-open it.

Thank you!

**Closed as completed by jajmo** 2019-07-30 15:36 UTC
